import type { Lang } from "@/lib/locale";

const en = {
  translate: "Translate to Filipino",
  nav: {
    path: "Path",
    labs: "Labs",
    glossary: "Glossary",
    milestones: "Milestones",
    about: "About",
    menu: "Open menu",
  },
  progress: "Progress",
  lessonsWord: "lessons",
  of: "of",
  min: "min",
  footer: "Free Crypto and Web3 education. Not financial advice. Public good.",
  tagline: "From zero knowledge to real impact.",
  home: {
    kicker: "Free academy",
    title: "From zero knowledge to real impact.",
    lede: "A calm path through Crypto and Web3. No hype cycle. No tickers. Ten chapters, three labs, and a glossary — from first question to first milestone you can actually defend.",
    start: "Start at zero",
    continue: "Continue",
    seePath: "See the path",
    seeMilestones: "See milestones",
    yourProgress: "Your progress",
    next: "Next",
    pathDone: "Path complete. Claim your milestones.",
    principles: [
      {
        n: "01",
        t: "Start at zero",
        d: "Money, ledgers, and why a shared computer is expensive on purpose. No assumed jargon.",
      },
      {
        n: "02",
        t: "Practice, don't just read",
        d: "Simulated wallet, transaction, and AMM labs. The chain out there is real. These are not.",
      },
      {
        n: "03",
        t: "Impact over speculation",
        d: "Milestones you can say out loud. Competence that leaks to the next person. Public good.",
      },
    ],
    thePath: "The path",
    ten: "Ten chapters. One line.",
    fullPath: "Full path",
    labs: "Labs",
    hands: "Hands on, funds off.",
    chain: "The chain is real. Start simulated.",
    then: "Then take a milestone that still matters if prices go nowhere.",
    continuePath: "Continue the path",
    begin: "Begin chapter 01",
  },
  path: {
    kicker: "Curriculum",
    title: "The path",
    lede: "Ten chapters from first principles to a personal milestone. Read in order if you are starting from zero. Skip ahead if you can pass the checks.",
    done: "Done",
    lab: "Lab",
    open: "Open chapter",
    view: "View",
    continueWith: "Continue with",
  },
  chapter: {
    of: (n: string) => `Chapter ${n} of 10`,
    start: "Start this chapter",
    read: "Read",
    lab: "Lab",
    milestones: "Milestones",
  },
  lesson: {
    check: "Check",
    passed: "Passed",
    question: "Question",
    checkAnswers: "Check answers",
    allCorrect: "All correct. Lesson marked complete.",
    tryAgain: "Try again",
    previous: "Previous",
    next: "Next",
    nextChapter: "Next chapter",
    pathComplete: "Path complete",
    seeMilestones: "See your milestones",
  },
  glossary: {
    kicker: "Reference",
    title: "Glossary",
    lede: (n: number) => `${n} terms, written to be used. Search, then read the short line first.`,
    searchLabel: "Search glossary",
    placeholder: "Search terms…",
    empty: "No matches. Try a shorter word — “gas”, “key”, “amm”.",
    related: "Related",
  },
  milestones: {
    kicker: "Impact",
    title: "Milestones",
    lede: "These are competencies, not badges. Claim one only if you can explain it out loud without the page in front of you.",
    complete: "Lessons complete",
    inReach: (a: number, b: number) => `${a} of ${b} milestones in reach.`,
    next: "Your next move",
    chapter: "Chapter",
    continue: "Continue",
    pathComplete: "Path complete",
    reading: "The reading is done. The work is not.",
    readingBody: "Restore a test wallet. Read a live transaction on an explorer. Teach one idea to someone else.",
    defend: "I can already defend this",
    resetConfirm: "Clear local progress on this device?",
    reset: "Reset local progress",
  },
  about: {
    kicker: "About",
    title: "A public good",
    p1: "Lumen is a free academy for Crypto and Web3. It exists because the field is loud, the failure modes are irreversible, and most “education” is a funnel to a product. We would rather you understand the machine.",
    p2: "The path runs from zero — what money is doing — through keys, Bitcoin, Ethereum, transactions, DeFi, culture, security, and governance, and ends on impact: a next move that still matters if prices go nowhere.",
    p3: "Labs on this site are simulations. They cannot control real funds. Do not paste a real seed phrase anywhere in this academy. Do not treat anything here as financial, legal, or tax advice.",
    p4: "Progress is stored in this browser only. There is no account. If that feels fragile, it is also honest: same as a seed, the state lives where you put it.",
    p5a: "If you already know a chapter, skip it — after you can pass the check. If you are starting from nothing, start at",
    p5b: "Zero",
  },
  labs: {
    eyebrow: "Lab",
    wallet: {
      title: "Wallet lab",
      short: "Wallet",
      lede: "Create a simulated key, read a twelve-word phrase, and practice a restore check.",
    },
    transaction: {
      title: "Transaction lab",
      short: "Transaction",
      lede: "Draft a transfer, sign it, and watch the states from mempool to block.",
    },
    amm: {
      title: "AMM lab",
      short: "AMM",
      lede: "Push size through a constant-product pool and watch the price move.",
    },
    sim: "Simulation",
    walletNote:
      "These twelve words cannot control real funds. A real wallet will look almost identical. Never type a live seed phrase into a tutorial — including this one.",
    newWallet: "New simulated wallet",
    hide: "Hide words",
    reveal: "Reveal words",
    derived: "Derived address (hash of the phrase, demo only)",
    prove: "Prove you can back it up",
    select: (nums: string) =>
      `Select words ${nums} in order — the same check a wallet does when you write a phrase down.`,
    orderOk: "Order matches. In real life, store the paper offline.",
    orderBad: "Wrong order. A real restore would fail — which is the point.",
    reset: "Reset",
    walletTips: [
      "The phrase is the master secret. Copies of it are extra attackers.",
      "Deleting the app does not move funds. Losing the phrase does.",
      "Screenshots sync to the cloud. That is not a backup. That is a leak.",
    ],
    txNote:
      "Nothing here is broadcast. Watch the states: signed locally, waiting in a public mempool, then included in a block. Pending is not settled.",
    from: "From",
    to: "To",
    deriving: "deriving…",
    amount: "Amount (ETH)",
    maxFee: (gwei: number) => `Max fee (${gwei} gwei)`,
    nonceLine: (n: number) => `Nonce ${n} · chain id 1 (demo)`,
    sign: "Sign and broadcast",
    newDraft: "New draft",
    hash: "Hash",
    value: "Value",
    status: "Status",
    block: "Block",
    pending: "pending",
    included: "Included (1 confirmation)",
    steps: { draft: "draft", signed: "signed", mempool: "mempool", included: "included" },
    txTips: [
      "Nonce orders your sends and stops replay of the same signature.",
      "The mempool is public. Do not put secrets in calldata.",
      "A failed contract call can still cost gas — the network did the work of trying.",
    ],
    constant: "Constant product",
    pool: (eth: number, usdc: string) =>
      `A pool with ${eth} ETH and ${usdc} USDC. The product x · y stays constant (minus a 0.3% fee). Larger trades walk further along the curve.`,
    reserve: (x: string) => `${x} ETH in reserve`,
    sell: "You sell ETH",
    receive: "You receive",
    spotBefore: "Spot before",
    spotAfter: "Spot after",
    impact: "Price impact",
    reserves: (eth: string, usdc: string, k: string) =>
      `Reserves become ${eth} ETH and ${usdc} USDC. k stays ${k}.`,
    curve:
      "Impact is not a person charging you extra. It is the curve. Thin liquidity or a large dx both steepen the walk. Slippage settings in a real wallet are a bound on this number — too loose, and a sandwich can take the slack.",
  },
};

const fil: typeof en = {
  translate: "Translate to English",
  nav: {
    path: "Landas",
    labs: "Mga lab",
    glossary: "Talasalitaan",
    milestones: "Mga yugto",
    about: "Tungkol",
    menu: "Buksan ang menu",
  },
  progress: "Progreso",
  lessonsWord: "aralin",
  of: "sa",
  min: "min",
  footer: "Libreng edukasyon sa Crypto at Web3. Hindi ito payo sa pananalapi. Pampublikong yaman.",
  tagline: "Mula sa zero na kaalaman hanggang sa tunay na epekto.",
  home: {
    kicker: "Libreng akademya",
    title: "Mula sa zero na kaalaman hanggang sa tunay na epekto.",
    lede: "Isang tahimik na landas sa Crypto at Web3. Walang hype. Walang ticker. Sampung kabanata, tatlong lab, at isang talasalitaan — mula sa unang tanong hanggang sa unang yugto na kaya mong ipagtanggol.",
    start: "Magsimula sa zero",
    continue: "Magpatuloy",
    seePath: "Tingnan ang landas",
    seeMilestones: "Tingnan ang mga yugto",
    yourProgress: "Ang iyong progreso",
    next: "Susunod",
    pathDone: "Tapos na ang landas. Kunin ang iyong mga yugto.",
    principles: [
      {
        n: "01",
        t: "Magsimula sa zero",
        d: "Pera, ledger, at kung bakit mahal ang isang pinagsasaluhang kompyuter. Walang ipinagpapalagay na jargon.",
      },
      {
        n: "02",
        t: "Magsanay, huwag lang magbasa",
        d: "Simulated na wallet, transaksyon, at AMM. Totoo ang chain sa labas. Hindi ang mga ito.",
      },
      {
        n: "03",
        t: "Epekto, hindi spekulasyon",
        d: "Mga yugtong masasabi nang malakas. Kakayahang maipapasa sa susunod. Pampublikong yaman.",
      },
    ],
    thePath: "Ang landas",
    ten: "Sampung kabanata. Isang linya.",
    fullPath: "Buong landas",
    labs: "Mga lab",
    hands: "Hawakan, huwag pondohan.",
    chain: "Totoo ang chain. Magsimula sa simulation.",
    then: "Pagkatapos, pumili ng yugto na mahalaga pa rin kahit hindi gumalaw ang presyo.",
    continuePath: "Ipagpatuloy ang landas",
    begin: "Simulan ang kabanata 01",
  },
  path: {
    kicker: "Kurikulum",
    title: "Ang landas",
    lede: "Sampung kabanata mula sa mga unang prinsipyo hanggang sa personal na yugto. Basahin nang sunod-sunod kung nagsisimula ka sa zero. Laktawan kung kaya mo ang mga pagsusulit.",
    done: "Tapos",
    lab: "Lab",
    open: "Buksan ang kabanata",
    view: "Tingnan",
    continueWith: "Magpatuloy sa",
  },
  chapter: {
    of: (n: string) => `Kabanata ${n} ng 10`,
    start: "Simulan ang kabanatang ito",
    read: "Nabasa",
    lab: "Lab",
    milestones: "Mga yugto",
  },
  lesson: {
    check: "Pagsusuri",
    passed: "Pumasa",
    question: "Tanong",
    checkAnswers: "Tingnan ang mga sagot",
    allCorrect: "Tama lahat. Minarkahang tapos ang aralin.",
    tryAgain: "Subukan muli",
    previous: "Nakaraan",
    next: "Susunod",
    nextChapter: "Susunod na kabanata",
    pathComplete: "Tapos na ang landas",
    seeMilestones: "Tingnan ang iyong mga yugto",
  },
  glossary: {
    kicker: "Sanggunian",
    title: "Talasalitaan",
    lede: (n: number) =>
      `${n} termino, para gamitin. Maghanap, tapos basahin muna ang maikling linya.`,
    searchLabel: "Hanapin sa talasalitaan",
    placeholder: "Maghanap ng termino…",
    empty: "Walang tugma. Subukan ang mas maikling salita — “gas”, “key”, “amm”.",
    related: "Kaugnay",
  },
  milestones: {
    kicker: "Epekto",
    title: "Mga yugto",
    lede: "Mga kakayahan ito, hindi badge. Kunin lang kung kaya mong ipaliwanag nang malakas nang hindi nakatingin sa pahina.",
    complete: "Mga araling tapos",
    inReach: (a: number, b: number) => `${a} sa ${b} na yugto ang abot.`,
    next: "Ang susunod mong hakbang",
    chapter: "Kabanata",
    continue: "Magpatuloy",
    pathComplete: "Tapos na ang landas",
    reading: "Tapos na ang pagbabasa. Hindi pa ang gawain.",
    readingBody:
      "Ibalik ang isang test wallet. Basahin ang isang live na transaksyon sa explorer. Ituro ang isang ideya sa iba.",
    defend: "Kaya ko nang ipagtanggol ito",
    resetConfirm: "Burahin ang lokal na progreso sa device na ito?",
    reset: "I-reset ang lokal na progreso",
  },
  about: {
    kicker: "Tungkol",
    title: "Isang pampublikong yaman",
    p1: "Ang Lumen ay libreng akademya para sa Crypto at Web3. Umiiral ito dahil maingay ang larangan, hindi na mababawi ang mga pagkakamali, at karamihan ng “edukasyon” ay daan lang patungo sa isang produkto. Mas gusto naming maunawaan mo ang makina.",
    p2: "Ang landas ay nagsisimula sa zero — kung ano ang ginagawa ng pera — dumadaan sa mga susi, Bitcoin, Ethereum, transaksyon, DeFi, kultura, seguridad, at pamamahala, at nagtatapos sa epekto: isang susunod na hakbang na mahalaga pa rin kahit hindi gumalaw ang presyo.",
    p3: "Simulation ang mga lab sa site na ito. Hindi nila makokontrol ang tunay na pondo. Huwag magdikit ng totoong seed phrase kahit saan sa akademyang ito. Huwag ituring ang anumang narito bilang payo sa pananalapi, batas, o buwis.",
    p4: "Ang progreso ay naka-imbak sa browser na ito lang. Walang account. Kung mukhang marupok, tapat din iyon: tulad ng seed, doon nakatira ang estado kung saan mo ito inilagay.",
    p5a: "Kung alam mo na ang isang kabanata, laktawan ito — pagkatapos mong mapasa ang pagsusuri. Kung nagsisimula ka sa wala, magsimula sa",
    p5b: "Zero",
  },
  labs: {
    eyebrow: "Lab",
    wallet: {
      title: "Lab ng wallet",
      short: "Wallet",
      lede: "Gumawa ng simulated na susi, basahin ang labindalawang salita, at sanayin ang pag-restore.",
    },
    transaction: {
      title: "Lab ng transaksyon",
      short: "Transaksyon",
      lede: "Gumawa ng padala, lagdaan ito, at panoorin mula mempool hanggang block.",
    },
    amm: {
      title: "Lab ng AMM",
      short: "AMM",
      lede: "Itulak ang laki sa constant-product pool at panoorin ang presyo.",
    },
    sim: "Simulation",
    walletNote:
      "Hindi makokontrol ng labindalawang salitang ito ang tunay na pondo. Halos kapareho ang itsura ng totoong wallet. Huwag kailanman i-type ang live na seed phrase sa isang tutorial — kasama ito.",
    newWallet: "Bagong simulated na wallet",
    hide: "Itago ang mga salita",
    reveal: "Ipakita ang mga salita",
    derived: "Hango na address (hash ng parirala, demo lang)",
    prove: "Patunayan na kaya mong i-backup",
    select: (nums: string) =>
      `Piliin ang mga salitang ${nums} ayon sa ayos — ang mismong pagsusuri ng wallet kapag isinusulat mo ang parirala.`,
    orderOk: "Tugma ang ayos. Sa totoong buhay, itago ang papel nang offline.",
    orderBad: "Maling ayos. Mababigo ang totoong restore — iyon ang punto.",
    reset: "I-reset",
    walletTips: [
      "Ang parirala ang master secret. Ang mga kopya nito ay dagdag na umaatake.",
      "Hindi gumagalaw ang pondo kapag binura ang app. Mawawala ang pondo kapag nawala ang parirala.",
      "Nagsi-sync sa cloud ang screenshot. Hindi iyon backup. Iyon ay tagas.",
    ],
    txNote:
      "Walang ibino-broadcast dito. Panoorin ang mga estado: nilagdaan sa lokal, naghihintay sa pampublikong mempool, tapos kasama sa isang block. Ang pending ay hindi pa settled.",
    from: "Mula",
    to: "Patungo",
    deriving: "hinuhugot…",
    amount: "Halaga (ETH)",
    maxFee: (gwei: number) => `Pinakamataas na bayad (${gwei} gwei)`,
    nonceLine: (n: number) => `Nonce ${n} · chain id 1 (demo)`,
    sign: "Lagdaan at i-broadcast",
    newDraft: "Bagong burador",
    hash: "Hash",
    value: "Halaga",
    status: "Katayuan",
    block: "Block",
    pending: "naghihintay",
    included: "Kasama na (1 kumpirmasyon)",
    steps: { draft: "burador", signed: "nilagdaan", mempool: "mempool", included: "kasama" },
    txTips: [
      "Inaayos ng nonce ang mga padala mo at pinipigilan ang replay ng parehong lagda.",
      "Pampubliko ang mempool. Huwag maglagay ng sikreto sa calldata.",
      "Maaari pa ring magbayad ng gas ang nabigong tawag sa kontrata — ginawa ng network ang trabaho.",
    ],
    constant: "Constant product",
    pool: (eth: number, usdc: string) =>
      `Isang pool na may ${eth} ETH at ${usdc} USDC. Nanatiling pareho ang produkto ng x · y (bawas ang 0.3% na bayad). Mas malalayong hakbang sa kurba ang malalaking trade.`,
    reserve: (x: string) => `${x} ETH sa reserba`,
    sell: "Ibinebenta mong ETH",
    receive: "Matatanggap mo",
    spotBefore: "Spot bago",
    spotAfter: "Spot pagkatapos",
    impact: "Epekto sa presyo",
    reserves: (eth: string, usdc: string, k: string) =>
      `Ang reserba ay magiging ${eth} ETH at ${usdc} USDC. Nanatili ang k sa ${k}.`,
    curve:
      "Hindi tao ang naniningil ng dagdag. Ang kurba iyon. Ang manipis na liquidity o malaking dx ay parehong tumitinding lakad. Ang slippage sa totoong wallet ay hangganan sa bilang na ito — masyadong maluwag, at maaaring kunin ng sandwich ang puwang.",
  },
};

export type Copy = typeof en;

export function getCopy(lang: Lang): Copy {
  return lang === "fil" ? fil : en;
}
