import type { GlossaryEntry } from "./types";

export const glossary: GlossaryEntry[] = [
  {
    id: "address",
    term: "Address",
    short: "A public identifier you can share so others can send you assets.",
    body: "An address is derived from a public key (usually by hashing it). It is safe to share. It is not a login, and it does not prove who you are in the legal sense — only that you control the matching private key.",
    related: ["public-key", "private-key", "wallet"],
  },
  {
    id: "amm",
    term: "Automated market maker (AMM)",
    short: "A pool of assets that prices trades with a formula instead of an order book.",
    body: "The classic Uniswap v2 rule is x · y = k: the product of the two reserves stays constant. Traders pay a fee; large trades move the price (price impact). An AMM is a program, not a person making a market.",
    related: ["liquidity", "slippage", "smart-contract"],
  },
  {
    id: "block",
    term: "Block",
    short: "A batch of transactions plus a link to the previous batch.",
    body: "A block contains transactions, a timestamp, a reference (hash) of the previous block, and whatever extra a protocol needs (nonce for proof of work, attestations for proof of stake). The chain of hashes is what makes history expensive to rewrite.",
    related: ["hash", "consensus", "confirmation"],
  },
  {
    id: "blockchain",
    term: "Blockchain",
    short: "A replicated ledger of blocks that many computers agree on.",
    body: "The useful property is not the data structure. It is that independent operators can verify the same history and reject invalid updates without a central editor. That is expensive. It is only worth it when you need that kind of agreement.",
    related: ["block", "consensus", "node"],
  },
  {
    id: "bridge",
    term: "Bridge",
    short: "Software that moves a representation of an asset from one chain to another.",
    body: "Most bridges lock an asset on chain A and mint a claim on chain B. The claim is only as good as the lock and the operators. Bridges have been a major source of losses. Treat them as a security decision, not a convenience.",
    related: ["smart-contract", "custody"],
  },
  {
    id: "consensus",
    term: "Consensus",
    short: "The rules by which a network agrees which block is next.",
    body: "Proof of work spends energy to make proposing a block costly. Proof of stake makes proposing a block a function of locked capital that can be slashed. Neither is magic: both are mechanisms for making disagreement expensive.",
    related: ["proof-of-work", "proof-of-stake", "block"],
  },
  {
    id: "confirmation",
    term: "Confirmation",
    short: "A transaction sitting in a block that the network is treating as canonical.",
    body: "One confirmation means “included in a block.” More confirmations mean more blocks built on top, which makes a reorg less likely. Exchanges often wait for several. Finality is a spectrum, not a stamp.",
    related: ["block", "reorg", "transaction"],
  },
  {
    id: "custody",
    term: "Custody",
    short: "Who can actually move the funds.",
    body: "Self-custody: you hold the keys. Custodial: an exchange or app holds them and owes you a balance. Neither is morally superior in every case. Self-custody removes counterparty risk and adds operational risk (loss, theft, inheritance).",
    related: ["wallet", "private-key", "seed-phrase"],
  },
  {
    id: "dao",
    term: "DAO",
    short: "A group that uses onchain rules to allocate resources or change a protocol.",
    body: "A DAO is not automatically democratic, efficient, or leaderless. Token voting can be plutocratic. Delegation can re-centralize. The interesting question is always: who can change the parameters, and who is harmed if they do.",
    related: ["governance", "token"],
  },
  {
    id: "defi",
    term: "DeFi",
    short: "Financial contracts that run as programs anyone can use, without a bank account.",
    body: "Lending, trading, and derivatives implemented as smart contracts. Access is open; recourse is not. You trade a human customer-support desk for code, oracles, and your own operational security.",
    related: ["amm", "smart-contract", "oracle"],
  },
  {
    id: "ecdsa",
    term: "ECDSA / secp256k1",
    short: "The signature scheme Bitcoin and Ethereum use to prove a key authorized a message.",
    body: "You do not need the math to use a wallet. You do need the idea: a signature is proof of control of a private key, without revealing the key. If the key leaks, signatures are free for the attacker.",
    related: ["private-key", "public-key", "transaction"],
  },
  {
    id: "erc20",
    term: "ERC-20",
    short: "A common Ethereum interface for fungible tokens.",
    body: "An ERC-20 contract keeps balances and lets you transfer, approve, and check allowances. The interface is a pattern, not a guarantee of quality. Anyone can deploy one. The contract’s code — and the people behind it — still matter.",
    related: ["token", "smart-contract", "approval"],
  },
  {
    id: "approval",
    term: "Token approval",
    short: "Permission for a contract to move tokens from your address.",
    body: "Approvals are how DEXs spend your tokens. Unlimited approvals are convenient and dangerous: a later bug or scam in that contract can drain the allowance. Review and revoke unused approvals.",
    related: ["erc20", "phishing", "smart-contract"],
  },
  {
    id: "gas",
    term: "Gas",
    short: "The unit of work an EVM transaction is allowed to consume, paid in the native coin.",
    body: "Gas exists so a public computer cannot be looped forever for free. You set a limit and a price (or a max fee under EIP-1559). Failed transactions can still cost gas: the network did the work of trying.",
    related: ["ethereum", "transaction", "eip1559"],
  },
  {
    id: "eip1559",
    term: "EIP-1559",
    short: "Ethereum’s fee market: a base fee that burns, plus an optional tip.",
    body: "The base fee rises and falls with demand and is burned. You add a priority fee so a proposer includes you. This replaced a lot of guess-the-gas-price behavior, but congestion still costs more.",
    related: ["gas", "ethereum"],
  },
  {
    id: "hash",
    term: "Hash",
    short: "A fingerprint of data that is easy to compute and hard to reverse.",
    body: "SHA-256 and keccak256 map any input to a fixed-size output. Change one bit, get a different fingerprint. Hashes glue blocks together, commit to data, and (with other steps) derive addresses.",
    related: ["block", "address"],
  },
  {
    id: "liquidity",
    term: "Liquidity",
    short: "How easily you can trade size without moving the price a lot.",
    body: "In an AMM, liquidity is the size of the reserves. Thin pools mean high price impact. Providing liquidity can earn fees and can also lose value versus holding (impermanent loss) if prices move.",
    related: ["amm", "slippage"],
  },
  {
    id: "mempool",
    term: "Mempool",
    short: "The waiting room of valid-but-not-yet-included transactions.",
    body: "Nodes keep a pool of candidates. Searchers and builders may reorder, include, or sandwich based on fees and content. Treat the mempool as public. Do not put secrets in calldata.",
    related: ["transaction", "mev"],
  },
  {
    id: "mev",
    term: "MEV",
    short: "Value extracted by choosing which transactions go into a block, and in what order.",
    body: "Originally “miner extractable value,” now usually “maximal.” It includes sandwiching DEX trades and liquidations. It is a property of transparent, ordered ledgers — not a bug you can wish away.",
    related: ["mempool", "block", "amm"],
  },
  {
    id: "nft",
    term: "NFT",
    short: "A token whose units are not interchangeable, often used for unique items.",
    body: "The token onchain is usually a pointer (token id + contract) plus metadata. The image file is often offchain. An NFT can represent membership, a license, art, or nothing much. Price is not the same as meaning.",
    related: ["token", "smart-contract"],
  },
  {
    id: "node",
    term: "Node",
    short: "Software that speaks the protocol: checks rules, stores data, gossips messages.",
    body: "Full nodes verify. Light clients verify less and trust more. Running a node is how you stop outsourcing truth to an API. Most wallets talk to someone else’s node — that is a trust choice.",
    related: ["blockchain", "consensus"],
  },
  {
    id: "nonce",
    term: "Nonce",
    short: "A number used once — in Ethereum accounts, the transaction count.",
    body: "Your next Ethereum transaction must use the next nonce. It prevents replay of the same signed payload. Stuck transactions are often nonce gaps or underpriced fees. In Bitcoin mining, “nonce” means something else: a field you grind for a valid hash.",
    related: ["transaction", "ethereum"],
  },
  {
    id: "oracle",
    term: "Oracle",
    short: "A way for a contract to learn facts about the outside world.",
    body: "Blockchains do not know prices, weather, or election results. Oracles import them. If the oracle is wrong or captured, the contract is wrong. DeFi risk often hides here.",
    related: ["defi", "smart-contract"],
  },
  {
    id: "phishing",
    term: "Phishing",
    short: "Tricking you into signing, approving, or revealing a secret.",
    body: "Fake sites, fake support, poisoned ads, lookalike tokens. The scam is rarely “break cryptography.” It is “get a human to authorize the theft.” Slow down. Check URLs. Read what you sign.",
    related: ["seed-phrase", "approval", "custody"],
  },
  {
    id: "private-key",
    term: "Private key",
    short: "A secret number that can sign messages for an account.",
    body: "Anyone with the private key is the account. There is no reset email. Hardware devices, well-designed wallets, and never typing a key into a website are the boring defenses that work.",
    related: ["public-key", "seed-phrase", "wallet"],
  },
  {
    id: "proof-of-stake",
    term: "Proof of stake",
    short: "Consensus where validators lock capital that can be destroyed for cheating.",
    body: "Ethereum switched from proof of work to proof of stake in 2022. Security comes from the cost of acquiring stake and the risk of slashing — plus the social layer that can still coordinate in a crisis.",
    related: ["consensus", "ethereum", "validator"],
  },
  {
    id: "proof-of-work",
    term: "Proof of work",
    short: "Consensus where proposing a block requires burning energy on a hard puzzle.",
    body: "Bitcoin still uses it. The puzzle is finding a nonce such that the block hash is below a target. Energy is the cost of rewriting history. Environmental debate is real; so is the simplicity of the mechanism.",
    related: ["consensus", "bitcoin", "hash"],
  },
  {
    id: "public-key",
    term: "Public key",
    short: "The counterpart of a private key; used to verify signatures and derive addresses.",
    body: "You can share a public key. You cannot usefully reverse it into a private key with known math. Wallets often hide this and show only an address.",
    related: ["private-key", "address", "ecdsa"],
  },
  {
    id: "reorg",
    term: "Reorg",
    short: "The network switching to a different, heavier (or more attested) chain tip.",
    body: "Short reorgs happen. Deep ones are rare and usually a crisis. This is why “one confirmation” is not the same as “settled for a house.”",
    related: ["confirmation", "block", "consensus"],
  },
  {
    id: "seed-phrase",
    term: "Seed phrase",
    short: "A list of words that encodes the master secret for a wallet.",
    body: "BIP-39 maps 12 or 24 words to entropy, then to keys. Anyone with the words can recreate the wallet. Write them on paper or metal, offline. Never in screenshots, chat, or a “support” form.",
    related: ["private-key", "wallet", "custody"],
  },
  {
    id: "slippage",
    term: "Slippage",
    short: "The difference between the price you expected and the price you got.",
    body: "Caused by other trades, thin liquidity, and your own size. Slippage settings that are too loose are an attack surface (sandwiches). Too tight and the swap fails.",
    related: ["amm", "mev", "liquidity"],
  },
  {
    id: "smart-contract",
    term: "Smart contract",
    short: "A program stored on a chain that anyone can call according to its rules.",
    body: "“Smart” is marketing. It is a program. It does what it is written to do, including the bugs. Upgradability, admin keys, and oracles reintroduce humans. Read the permissions, not the landing page.",
    related: ["ethereum", "gas", "oracle"],
  },
  {
    id: "token",
    term: "Token",
    short: "A ledger entry representing a claim, unit, or item, usually implemented by a contract.",
    body: "Native coins (BTC, ETH) are part of the protocol. Tokens (ERC-20, etc.) are applications. A token can be a currency, a vote, a ticket, or a speculative chip. The code and the social agreement decide which.",
    related: ["erc20", "nft", "governance"],
  },
  {
    id: "transaction",
    term: "Transaction",
    short: "A signed request to change the ledger.",
    body: "It names an action (send value, call a contract), a fee, and a nonce, and it carries a signature. Nodes check the signature and the rules, then gossip it. Inclusion is not instant and not guaranteed at a given fee.",
    related: ["signature", "gas", "mempool"],
  },
  {
    id: "signature",
    term: "Signature",
    short: "Proof that a private key authorized a specific message.",
    body: "Blind signing is how people lose funds: a site shows a picture, the wallet shows hex, you tap confirm. Read typed data. If you cannot parse it, do not sign it.",
    related: ["ecdsa", "phishing", "transaction"],
  },
  {
    id: "utxo",
    term: "UTXO",
    short: "Bitcoin’s model: coins as unspent outputs, not account balances.",
    body: "You spend whole outputs and create new ones (including change). This is different from Ethereum’s account balance model. Both are ledgers; they just bookkeep differently.",
    related: ["bitcoin", "transaction"],
  },
  {
    id: "validator",
    term: "Validator",
    short: "A participant that proposes or attests to blocks under proof of stake.",
    body: "Validators lock stake. Misbehavior can be slashed. Home staking, pooled staking, and liquid staking change who holds the keys and who takes the risk.",
    related: ["proof-of-stake", "ethereum"],
  },
  {
    id: "wallet",
    term: "Wallet",
    short: "Software or hardware that holds keys and helps you sign.",
    body: "A wallet does not contain coins. The chain does. The wallet holds the secrets that can move them, and a view of your balances from a node or indexer. Hardware wallets keep keys offline; they do not make you invincible if you sign a bad payload.",
    related: ["private-key", "seed-phrase", "custody"],
  },
  {
    id: "bitcoin",
    term: "Bitcoin",
    short: "The first widely used public blockchain: a scarce digital bearer asset and settlement network.",
    body: "Launched in 2009 from a 2008 paper. Proof of work, ~10 minute blocks, a 21 million issuance cap, UTXO accounting. It is not a general-purpose computer. That constraint is part of the design.",
    related: ["proof-of-work", "utxo", "block"],
  },
  {
    id: "ethereum",
    term: "Ethereum",
    short: "A public computer that holds accounts, code, and a native coin used to pay for gas.",
    body: "Smart contracts, an account model, and (since 2022) proof of stake. It is more flexible than Bitcoin and more complex. Complexity is both the product and the risk.",
    related: ["smart-contract", "gas", "proof-of-stake"],
  },
  {
    id: "governance",
    term: "Governance",
    short: "How a protocol changes — votes, councils, or “we do not change it.”",
    body: "Bitcoin’s social conservatism is a governance choice. A DAO with a 1-of-n admin key is also a choice. Read who can upgrade the contracts before you depend on them.",
    related: ["dao", "token"],
  },
  {
    id: "l2",
    term: "Layer 2",
    short: "A system that inherits security from a base chain while executing more cheaply off of it.",
    body: "Rollups post data or proofs to Ethereum so you can recover state if the operator disappears — in theory. Designs differ (optimistic vs. validity proofs, where data lives). “L2” on a marketing site is not a proof.",
    related: ["ethereum", "bridge"],
  },
];
