/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as PathRouteImport } from './routes/path'
import { Route as LabLabIdRouteImport } from './routes/lab.$labId'
import { Route as LearnChapterIdRouteImport } from './routes/learn.$chapterId'
import { Route as LearnChapterIdIndexRouteImport } from './routes/learn.$chapterId.index'
import { Route as LearnChapterIdLessonIdRouteImport } from './routes/learn.$chapterId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLabIdRoute = LabLabIdRouteImport.update({
  id: '/lab/$labId',
  path: '/lab/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnChapterIdRoute = LearnChapterIdRouteImport.update({
  id: '/learn/$chapterId',
  path: '/learn/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnChapterIdIndexRoute = LearnChapterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnChapterIdRoute,
} as any)
const LearnChapterIdLessonIdRoute = LearnChapterIdLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => LearnChapterIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/milestones': typeof MilestonesRoute
  '/path': typeof PathRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/learn/$chapterId': typeof LearnChapterIdRouteWithChildren
  '/learn/$chapterId/$lessonId': typeof LearnChapterIdLessonIdRoute
  '/learn/$chapterId/': typeof LearnChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/milestones': typeof MilestonesRoute
  '/path': typeof PathRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/learn/$chapterId/$lessonId': typeof LearnChapterIdLessonIdRoute
  '/learn/$chapterId': typeof LearnChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/milestones': typeof MilestonesRoute
  '/path': typeof PathRoute
  '/lab/$labId': typeof LabLabIdRoute
  '/learn/$chapterId': typeof LearnChapterIdRouteWithChildren
  '/learn/$chapterId/$lessonId': typeof LearnChapterIdLessonIdRoute
  '/learn/$chapterId/': typeof LearnChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/glossary'
    | '/milestones'
    | '/path'
    | '/lab/$labId'
    | '/learn/$chapterId'
    | '/learn/$chapterId/$lessonId'
    | '/learn/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/glossary'
    | '/milestones'
    | '/path'
    | '/lab/$labId'
    | '/learn/$chapterId/$lessonId'
    | '/learn/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/glossary'
    | '/milestones'
    | '/path'
    | '/lab/$labId'
    | '/learn/$chapterId'
    | '/learn/$chapterId/$lessonId'
    | '/learn/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GlossaryRoute: typeof GlossaryRoute
  MilestonesRoute: typeof MilestonesRoute
  PathRoute: typeof PathRoute
  LabLabIdRoute: typeof LabLabIdRoute
  LearnChapterIdRoute: typeof LearnChapterIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$labId': {
      id: '/lab/$labId'
      path: '/lab/$labId'
      fullPath: '/lab/$labId'
      preLoaderRoute: typeof LabLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$chapterId': {
      id: '/learn/$chapterId'
      path: '/learn/$chapterId'
      fullPath: '/learn/$chapterId'
      preLoaderRoute: typeof LearnChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$chapterId/': {
      id: '/learn/$chapterId/'
      path: '/'
      fullPath: '/learn/$chapterId/'
      preLoaderRoute: typeof LearnChapterIdIndexRouteImport
      parentRoute: typeof LearnChapterIdRoute
    }
    '/learn/$chapterId/$lessonId': {
      id: '/learn/$chapterId/$lessonId'
      path: '/$lessonId'
      fullPath: '/learn/$chapterId/$lessonId'
      preLoaderRoute: typeof LearnChapterIdLessonIdRouteImport
      parentRoute: typeof LearnChapterIdRoute
    }
  }
}

interface LearnChapterIdRouteChildren {
  LearnChapterIdLessonIdRoute: typeof LearnChapterIdLessonIdRoute
  LearnChapterIdIndexRoute: typeof LearnChapterIdIndexRoute
}

const LearnChapterIdRouteChildren: LearnChapterIdRouteChildren = {
  LearnChapterIdLessonIdRoute: LearnChapterIdLessonIdRoute,
  LearnChapterIdIndexRoute: LearnChapterIdIndexRoute,
}

const LearnChapterIdRouteWithChildren = LearnChapterIdRoute._addFileChildren(
  LearnChapterIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GlossaryRoute: GlossaryRoute,
  MilestonesRoute: MilestonesRoute,
  PathRoute: PathRoute,
  LabLabIdRoute: LabLabIdRoute,
  LearnChapterIdRoute: LearnChapterIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
